/*
 * Generated by JasperReports - 12/6/18 2:44 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.bekasidev.app.model.WajibPajak;
import com.bekasidev.app.model.Pegawai;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;


/**
 *
 */
public class ReportPeminjamanBuku_1544082272896_221005 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_nomor_sp = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_penandatangan = null;
    private JRFillParameter parameter_jabatan_penandatangan = null;
    private JRFillParameter parameter_tanggal_surat = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_wajib_pajak = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_nomor_surat = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_nama_penandatangan = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_tanggal_sp = null;
    private JRFillParameter parameter_pangkat_penandatangan = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_jabatan_penandatangan_ttd = null;
    private JRFillParameter parameter_buku_peminjaman = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_MASTER_CURRENT_PAGE = null;
    private JRFillVariable variable_MASTER_TOTAL_PAGES = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_nomor_sp = (JRFillParameter)pm.get("nomor_sp");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_penandatangan = (JRFillParameter)pm.get("penandatangan");
        parameter_jabatan_penandatangan = (JRFillParameter)pm.get("jabatan_penandatangan");
        parameter_tanggal_surat = (JRFillParameter)pm.get("tanggal_surat");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_wajib_pajak = (JRFillParameter)pm.get("wajib_pajak");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_nomor_surat = (JRFillParameter)pm.get("nomor_surat");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_nama_penandatangan = (JRFillParameter)pm.get("nama_penandatangan");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_tanggal_sp = (JRFillParameter)pm.get("tanggal_sp");
        parameter_pangkat_penandatangan = (JRFillParameter)pm.get("pangkat_penandatangan");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_jabatan_penandatangan_ttd = (JRFillParameter)pm.get("jabatan_penandatangan_ttd");
        parameter_buku_peminjaman = (JRFillParameter)pm.get("buku_peminjaman");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_MASTER_CURRENT_PAGE = (JRFillVariable)vm.get("MASTER_CURRENT_PAGE");
        variable_MASTER_TOTAL_PAGES = (JRFillVariable)vm.get("MASTER_TOTAL_PAGES");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "C:\\Users\\Bayu Arafli\\Documents\\NetBeansProjects\\pajak-simulator\\src\\main\\resources\\images\\logo_kab_bekasi.png"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Cikarang Pusat, " + ((java.lang.String)parameter_tanggal_surat.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Pengelola " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Kec. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getKecamatan(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "973 / " + ((java.lang.String)parameter_nomor_surat.getValue()) + " / Bapenda"; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "NPWPD : " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Jl. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getJalan(); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sehubungan dengan Surat Perintah Pemeriksaan Pajak Daerah dari " + ((java.lang.String)parameter_jabatan_penandatangan.getValue()) + " Daerah Kabupaten Bekasi :"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "800 / " + ((java.lang.String)parameter_nomor_sp.getValue()) + " / Bapenda"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_tanggal_sp.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = "Cikarang Pusat, "; //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((net.sf.jasperreports.engine.data.JRBeanCollectionDataSource)parameter_buku_peminjaman.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=29$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "C:\\Users\\Bayu Arafli\\Documents\\NetBeansProjects\\pajak-simulator\\src\\main\\resources\\images\\logo_kab_bekasi.png"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Cikarang Pusat, " + ((java.lang.String)parameter_tanggal_surat.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Pengelola " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Kec. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getKecamatan(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "973 / " + ((java.lang.String)parameter_nomor_surat.getValue()) + " / Bapenda"; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "NPWPD : " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Jl. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getJalan(); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sehubungan dengan Surat Perintah Pemeriksaan Pajak Daerah dari " + ((java.lang.String)parameter_jabatan_penandatangan.getValue()) + " Daerah Kabupaten Bekasi :"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "800 / " + ((java.lang.String)parameter_nomor_sp.getValue()) + " / Bapenda"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_tanggal_sp.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = "Cikarang Pusat, "; //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((net.sf.jasperreports.engine.data.JRBeanCollectionDataSource)parameter_buku_peminjaman.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=29$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = "C:\\Users\\Bayu Arafli\\Documents\\NetBeansProjects\\pajak-simulator\\src\\main\\resources\\images\\logo_kab_bekasi.png"; //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "Cikarang Pusat, " + ((java.lang.String)parameter_tanggal_surat.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = "Pengelola " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = "Kec. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getKecamatan(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = "973 / " + ((java.lang.String)parameter_nomor_surat.getValue()) + " / Bapenda"; //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "NPWPD : " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = "Jl. " + ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getJalan(); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Sehubungan dengan Surat Perintah Pemeriksaan Pajak Daerah dari " + ((java.lang.String)parameter_jabatan_penandatangan.getValue()) + " Daerah Kabupaten Bekasi :"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "800 / " + ((java.lang.String)parameter_nomor_sp.getValue()) + " / Bapenda"; //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_tanggal_sp.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNpwpd(); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((com.bekasidev.app.model.WajibPajak)parameter_wajib_pajak.getValue()).getNamaWajibPajak(); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = "Cikarang Pusat, "; //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((net.sf.jasperreports.engine.data.JRBeanCollectionDataSource)parameter_buku_peminjaman.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNamaPegawai(); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = "NIP. " + ((com.bekasidev.app.model.Pegawai)parameter_penandatangan.getValue()).getNipPegawai(); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_pangkat_penandatangan.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_jabatan_penandatangan_ttd.getValue()) + " DAERAH KABUPATEN BEKASI"; //$JR_EXPR_ID=29$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
