/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bekasidev.app.view.masterview;

/**
 *
 * @author USER
 */
public class ToolsButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToolsButtonPanel
     */
    public ToolsButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahWPBtn = new javax.swing.JButton();

        tambahWPBtn.setText("tambah wp");
        tambahWPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahWPBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(tambahWPBtn)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(tambahWPBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahWPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahWPBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("tambah wp button clicked");
        WPInputFrame wPInputFrame = new WPInputFrame();
        wPInputFrame.setVisible(true);
    }//GEN-LAST:event_tambahWPBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tambahWPBtn;
    // End of variables declaration//GEN-END:variables
}
