/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.bekasidev.app.view.masterview;

import com.bekasidev.app.model.WajibPajak;
import com.bekasidev.app.service.ServiceFactory;
import com.bekasidev.app.service.backend.WajibPajakService;
import com.bekasidev.app.view.util.ComponentCollectorProvider;
import java.awt.Dimension;

/**
 *
 * @author USER
 */
public class WPInputFrame extends javax.swing.JFrame {
    private WajibPajakService wajibPajakService;

    /** Creates new form WPInputFrame */
    public WPInputFrame() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        Dimension screenSize = this.getToolkit().getScreenSize();
        int x = (int) screenSize.getWidth() / 2 - this.getWidth() / 2;
        int y = (int) screenSize.getHeight() / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
        
        this.setTitle("Form tambah wajib pajak");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        npwpdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaWPField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alamatWPField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        desaWPField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kecamatanWPField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jenisWPField = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("NPWPD");

        npwpdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npwpdFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama WP");

        jLabel3.setText("Alamat");

        jLabel4.setText("Desa/Kelurahan");

        jLabel5.setText("Kecamatan");

        kecamatanWPField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatanWPFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis WP");

        jenisWPField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restoran", "Hotel", "Parkir", "Hiburan", "Penerangan Jalan" }));

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        batalBtn.setText("batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(batalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpanBtn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(npwpdField)
                        .addComponent(namaWPField)
                        .addComponent(alamatWPField)
                        .addComponent(desaWPField)
                        .addComponent(kecamatanWPField)
                        .addComponent(jenisWPField, 0, 329, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npwpdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaWPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatWPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desaWPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kecamatanWPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisWPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalBtn)
                    .addComponent(simpanBtn))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void npwpdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npwpdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npwpdFieldActionPerformed

    private void kecamatanWPFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatanWPFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatanWPFieldActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        wajibPajakService = ServiceFactory.getWajibPajakService();
        if (!(npwpdField.getText().equals("")
                || namaWPField.getText().equals("")
                || desaWPField.getText().equals("")
                || kecamatanWPField.getText().equals("")
                || alamatWPField.getText().equals(""))) {
            
            WajibPajak wajibPajak = new WajibPajak();
            wajibPajak.setIdWajibPajak(npwpdField.getText());
            wajibPajak.setNamaWajibPajak(namaWPField.getText());
            wajibPajak.setJalan(alamatWPField.getText());
            wajibPajak.setDesa(desaWPField.getText());
            wajibPajak.setKecamatan(kecamatanWPField.getText());
            
            if (jenisWPField.getSelectedItem().toString().equals("Restoran")) {
                wajibPajak.setJenisWp((short)0);
            }
            else if (jenisWPField.getSelectedItem().toString().equals("Hotel")) {
                wajibPajak.setJenisWp((short)1);
            }
            else if(jenisWPField.getSelectedItem().toString().equals("Parkir")) {
                wajibPajak.setJenisWp((short)2);
            }
            else if (jenisWPField.getSelectedItem().toString().equals("Hiburan")) {
                wajibPajak.setJenisWp((short)3);
            }
            else if (jenisWPField.getSelectedItem().toString().equals("Penerangan Jalan")) {
                wajibPajak.setJenisWp((short)4);
            }
            
            wajibPajakService.createDataWP(wajibPajak);
            System.out.println("wajib pajak berhasil dibuat");
            this.dispose();
            
            MasterWpTableComponent masterWpTableComponent
                    = (MasterWpTableComponent) ComponentCollectorProvider
                    .getComponentMapper()
                    .get("master_wp_table_component")
                    .getComponent();
            MasterWPPanel masterWPPanel
                    = (MasterWPPanel) ComponentCollectorProvider
                    .getComponentMapper()
                    .get("master_wp_panel")
                    .getComponent();
            masterWPPanel.remove(masterWpTableComponent);
            ComponentCollectorProvider
                    .getComponentMapper()
                    .remove("master_wp_table_component");
            MasterWpTableComponent newMasterWPPanel 
                    = new MasterWpTableComponent();
            masterWPPanel.add(newMasterWPPanel);
            masterWPPanel.invalidate();
            masterWPPanel.revalidate();
            masterWPPanel.repaint();
                        
        }
        else {
            //ada field yang kosong
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatWPField;
    private javax.swing.JButton batalBtn;
    private javax.swing.JTextField desaWPField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenisWPField;
    private javax.swing.JTextField kecamatanWPField;
    private javax.swing.JTextField namaWPField;
    private javax.swing.JTextField npwpdField;
    private javax.swing.JButton simpanBtn;
    // End of variables declaration//GEN-END:variables

}
